// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7cDdR7CTbZXTYNrT5-xaOH2qLLolnuHo',
    appId: '1:626010001146:web:c9d47f57ffb029708d8343',
    messagingSenderId: '626010001146',
    projectId: 'praktikum10-f8492',
    authDomain: 'praktikum10-f8492.firebaseapp.com',
    storageBucket: 'praktikum10-f8492.appspot.com',
    measurementId: 'G-9FYH21W8TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtuPiVM427_0-ZaiYbPpAolTnFRFdGdOk',
    appId: '1:626010001146:android:28068f40a24bed518d8343',
    messagingSenderId: '626010001146',
    projectId: 'praktikum10-f8492',
    storageBucket: 'praktikum10-f8492.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpGF0Dww-r8vZ56RtEsoP08gHuOkCmR-4',
    appId: '1:626010001146:ios:d13e72ec8405c5c58d8343',
    messagingSenderId: '626010001146',
    projectId: 'praktikum10-f8492',
    storageBucket: 'praktikum10-f8492.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpGF0Dww-r8vZ56RtEsoP08gHuOkCmR-4',
    appId: '1:626010001146:ios:d13e72ec8405c5c58d8343',
    messagingSenderId: '626010001146',
    projectId: 'praktikum10-f8492',
    storageBucket: 'praktikum10-f8492.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
